### ISSUE TITLE
Dialogs feature

### ISSUE THREAD

**Issue by swarakaka** [inertiajs/inertia-django#11]
Hello @BrandonShar 

as you can see, Inertiajs version 1.0.0 will be available soon. Most likely, as they have identified for this version, the dialogs feature will be made available. Are there any plans to add that feature to Django as well?

[Dialogs](https://github.com/inertiajs/inertia-laravel/tree/dialog)

**Comment by BrandonShar** [comment]
Absolutely! The goal for both the Django and Rails Inertia packages is to always have feature parity with the Laravel version (even if we don't always implement things exactly the same). Thanks for the link!

**Comment by BrandonShar** [comment]
Closing this, but will re-open if I notice some momentum towards releasing Dialogs.
