### ISSUE TITLE
[Feature Request] Django requests not compatible with interia request payloads?

### ISSUE THREAD

**Issue by ChristopherBrownie** [inertiajs/inertia-django#21]
I've run into another snag. When attempting to post interia js forms the django request only includes the payload in a raw bytestring via `request.body`.

```js
const form = useForm({
    key: 'value'
});
form.post(usePage().url);
```

`request.POST` is empty as that's only populated from traditional form submissions. I'm unable to access `key` param in the view without processing the `request.body` bytestring first, which seems totally out of scope for individual projects to handle. DRF has solutions for this, but DRF shouldn't necessarily be required for this adapter to work I wouldn't think? Is there a way for the adapter to handle this?

**Comment by ChrisxHart** [comment]
Per discord conversation, this is what I have so far (maybe a naive implementation) which could hopefully give people access to inertia request data out of the box.

```python
# settings.py - Setting for parsing application/json requests and placing data in request.JSON. If you are using something like Django Rest Framework, this is done already and available through request.data, so it can be disabled here.
INERTIA_PARSE_JSON_REQUEST = True

# middleware.py
if settings.INERTIA_PARSE_JSON_REQUST and request.body and 'application/json' in request.content_type:
    try:
        request.JSON = json.loads(request.body)
    except json.JSONDecodeError:
        request.JSON = {}
```

**Comment by svengt** [comment]
@ChrisxHart You can pass the following argument to `form.post` to make the request compatible with Django.

```javascript
form.post(usePage().url, { forceFormData: true });
```

**Comment by BrandonShar** [comment]
I like the idea of baking some json support into Inertia Django because it's such a tightly coupled concept. 

@svengt's solution is perfect if you want to maintain Django standards, but for those who don't, I think I'm going to add something very similar to what @ChrisxHart wrote there into core. It'll probably be a very similar syntax, just lazily evaluated.

Thanks both of you, I'll leave this open until I have a PR up.

**Comment by BrandonShar** [comment]
closing per #30
