### ISSUE TITLE
Django Template with Svelte and SSR

### ISSUE THREAD

**Issue by pmdevita** [inertiajs/inertia-django#22]
Thought I'd leave this here, this is a template I made for getting set up with Svelte. It also has instructions on how to get the current SSR implementation working. 

https://github.com/pmdevita/Django-Svelte-Template

To quickstart, just run `django-admin startproject --template https://github.com/pmdevita/django-svelte-template/archive/master.zip my_django_project .`

**Comment by BrandonShar** [comment]
This is awesome, thanks! If you'd like to PR it to a new section in the Readme, I'd happily merge it!

**Comment by pmdevita** [comment]
Closing this since the Readme changes were merged

**Comment by laith43d** [comment]
any chance to run svelte with typescript instead of javascript?
