### ISSUE TITLE
Create a partial template

### ISSUE THREAD

**Issue by helixaros** [inertiajs/inertia-django#23]
How can I create only a small sub-set of a Django Template View to be handled by inertia?
Or is that not possible?

Essentially lets say that I have a Form that I want to be fully handled by Django, but in that form there is a multi dropdown element that I want to be handled by inertia (as the dropdown would send and requests to the server, and would use react to populate the dropdown). 
How can I accomplish something like that ? Or is this not the scope of inertia?

**Comment by jamiroph** [comment]
Purely opinion but..

Inertia isn't the right tool for the job here, You're effectively wanting to use the underlying features that SPA's funciton on (asynchronous javascript calls) by implementing the entire frontend framework.

If you only want to have a single form fetch data via AJAX then you'd be better off using plain Javascript/Typescript (depending on what flavour you already have as you've mentioned react here?) support for it (which is fairly rohbust feature-wise these days) or jQuery with its AJAX library.
