### ISSUE TITLE
Object of type ImageFieldFile is not JSON serializable

### ISSUE THREAD

**Issue by swarakaka** [inertiajs/inertia-django#4]
If the field type is Image, it returns a type error
```
Request Method: | GET
http://127.0.0.1:8000/
4.1.1
TypeError
Object of type ImageFieldFile is not JSON serializable
```

[I think this is the solution](https://stackoverflow.com/a/7618475)
But I have no idea how to adapt it to inertia.

**Comment by swarakaka** [comment]
Thank you very much, problem solved.

**Comment by progressify** [comment]
> Python is much too picky about what it json encodes for my liking smile
> 
> Your solution looks good to me! In order to add it to Inertia, you'll need to write it as a JsonEncoder class and then set that class as your `INERTIA_JSON_ENCODER` in your settings.
> 
> I didn't test this, so it likely needs some debugging, but I think an implementation would look something like this:
> 
> ```python
> from inertia.utils import InertiaJsonEncoder
> from django.db.models.fields.files import ImageFieldFile
> 
> class ImageFieldFileAwareJsonEncoder(InertiaJsonEncoder):
>    def default(self, value):
>       if isinstance(value, ImageFieldFile):
>          return value.path
>       
>       return super().default(value)
> ```
> 
> And then in your settings file
> 
> ```python
> from your.app.path import ImageFieldFileAwareJsonEncoder
> 
> INERTIA_JSON_ENCODER = ImageFieldFileAwareJsonEncoder
> ```
> 
> Hope that helps!

Same problem here, but with `AnonymousUser`
We must check all instances of the classes not JsonSerializable in the encoder?
