### ISSUE TITLE
Any future support for FastAPI?

### ISSUE THREAD

**Issue by NickDatLe** [inertiajs/inertia-django#42]
Hi - I know this is the Django project, but is there any plans to support FastAPI? With the AI boom, a lot of companies are using FastAPI.

**Comment by BrandonShar** [comment]
Hey @NickDatLe I'd be happy to help create an inertia library for FastAPI, but I don't have any experience using the framework myself. Would you be interested in collaborating?

**Comment by NickDatLe** [comment]
I think that would be a good weekend project. How do you suggest we get started?

**Comment by shininglove** [comment]
@hxjo just wanted to say this repo is so amazing, really well documented and works so well!

**Comment by BrandonShar** [comment]
Closing per @hxjo already having a great library up and running!
