### ISSUE TITLE
Add Support for Django 5.X

### ISSUE THREAD

**Issue by midsonlajeanty** [inertiajs/inertia-django#47]
I would to use inertia with django 5.X with Poetry i cannot installed package becouse inertia-django only support django>=4

**Comment by eddyojb88** [comment]
Does this mean Django 5 doesn't work with inertia-django?

**Comment by midsonlajeanty** [comment]
No the constraint >=4 allows both version 4 and version 5 to be supported

**Comment by pmdevita** [comment]
This should have been fixed in my PR from a while ago https://github.com/inertiajs/inertia-django/pull/35 I'm not having any trouble using the most recent release with 5

**Comment by BrandonShar** [comment]
Thanks @pmdevita, that explains it!
