### ISSUE TITLE
How would you use inertia with webpack?

### ISSUE THREAD

**Issue by darinkishore** [inertiajs/inertia-django#5]
Hi! I only see the vite example for the frontend. Can you use webpack as well?

**Comment by BrandonShar** [comment]
Absolutely! We actually used to prefer Webpack, but after Rails dropped it we started using Vite for all of our new applications. 

I'm not very familiar with what Webpack integrations exist for Django, but the inertia javascript entrypoint should be very similar. Off the top of my head, I think only the imports would change. [This folder](https://github.com/inertiajs/inertia-rails/tree/master/lib/generators/inertia_rails/install) has examples of what the various inertia.jsx files looked like when we were using Webpack as the default.
