### ISSUE TITLE
Call get_token() automatically

### ISSUE THREAD

**Issue by dankuck** [inertiajs/inertia-django#9]
The middleware should call `django.middleware.csrf.get_token(request)`. This will ensure a CSRF token is generated for the front end to find. Without some call to this method, the cookie will not be set.

> CsrfViewMiddleware sends this cookie with the response whenever django.middleware.csrf.get_token() is called. 

https://docs.djangoproject.com/en/4.1/ref/csrf/

**Comment by BrandonShar** [comment]
Thanks for the issue! My initial instinct is that the specific implementation of the CSRF token is outside the scope of the inertia middleware... what do you think?

**Comment by dankuck** [comment]
My impression is that Inertia's intention to be the glue that holds front and backend together is a "it just works" kind of mission.

According to the [docs](https://inertiajs.com/csrf-protection#top), the Laravel implementation does that for CSRF tokens.
<img width="628" alt="image" src="https://user-images.githubusercontent.com/277837/203589356-b0669fbf-13cf-4d2e-8bbd-21f0602927db.png">

But it may be sufficient for Inertia Django to specifically explain how to use CSRF tokens in the documentation.

The intended flow for a Django application to use CSRF is:
* Install the CSRF middleware
* Call get_token() in a view and pass the result to the template to render
* Include the token in any forms with POST/PUT/DELETE

The flow for an application using Inertia Django is:
* Install the CSRF middleware
* Call get_token() to set the cookie in any view that resolves to a front end page that will need one; ignore the return value
* Ensure the front end is configured to use the CSRF cookie with all POST/PUT/DELETE calls

The second bullet point can be replaced with a middleware that just always calls get_token() as Laravel does. 

The third bullet point is mentioned in the docs for CSRF on inertiajs.com, but since Django uses a different cookie name, setup for that probably needs to be addressed in documentation at least.

**Comment by MichaelNZ85** [comment]
I am having this problem as well. The CSRF token is set in the cookie in the POST request I'm sending, but Django isn't recognising it.

![firefox_E1stbrZ15B](https://user-images.githubusercontent.com/15241383/204127325-d3a161d5-3816-4b11-96e4-1d0be8bd1157.png)

Any help here would be great

**Comment by BrandonShar** [comment]
@dankuck ahh, I understand! I believe I have some circumstances in another app that lead me to believe this was working when it wasn't! 

A slight tweak to your flow with the django intended behavior: the `get_token` process isn't meant to be called manually in a normal django app, it happens automatically when you include the csrf template tag in your templates. Because we don't use templates, we need to substitute this behavior. 

Thanks for reporting, I'll get a fix up for this!


@MichaelNZ85 I believe your issue is unrelated. Django doesn't expect you to be sending the CSRF Token via a cookie header, it should be sent via an `'X-CSRFToken` header.

**Comment by BrandonShar** [comment]
Ok, I dug into this behavior a bit further and decided that the "django way" is to use the `ensure_csrf_cookie` decorator on any login views or public form views.

I'm currently deciding if this is unreasonable for the user and if Inertia should handle this. Part of what I'm wondering is if there is a drawback to generating and sending the token if a user doesn't want one...

**Comment by dankuck** [comment]
I see it: https://docs.djangoproject.com/en/1.8/ref/csrf/

I think there's no drawback, but I'm in favor of keeping the Django way, if only we point to that in the documentation
